int controller_loadFromText(char* path , LinkedList* pArrayListEmployee);
int controller_loadFromBinary(char* path , LinkedList* pArrayListEmployee);
int controller_addEmployee(LinkedList* pArrayListEmployee, int* idMax);
int controller_editEmployee(LinkedList* pArrayListEmployee, int* idMax);
int controller_removeEmployee(LinkedList* pArrayListEmployee, int* idMax);
int controller_ListEmployee(LinkedList* pArrayListEmployee);
int controller_sortEmployee(LinkedList* pArrayListEmployee);
int controller_saveAsText(char* path , LinkedList* pArrayListEmployee, int* idMax);
int controller_saveAsBinary(char* path , LinkedList* pArrayListEmployee, int* idMax);
int controller_id(LinkedList* pArrayListEmployee, int* idMax);
